{% set version = "1.0.0" %}

package:
  name: r-rnaturalearthdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rnaturalearthdata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rnaturalearthdata/rnaturalearthdata_{{ version }}.tar.gz
  sha256: e1fefaf1ea575fe242402c933b531c90f0f18772f8efe47b97a221b7eefb1e4d

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-sp >=1.0.15
  run:
    - r-base
    - r-sp >=1.0.15

test:
  commands:
    - $R -e "library('rnaturalearthdata')"

about:
  home: https://github.com/ropenscilabs/rnaturalearthdata
  license: CC0-1.0
  license_file: LICENSE
  summary: Vector map data from <http://www.naturalearthdata.com/>. Access functions are provided in the accompanying package 'rnaturalearth'.

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# The original CRAN metadata for this package was:

# Package: rnaturalearthdata
# Title: World Vector Map Data from Natural Earth Used in 'rnaturalearth'
# Version: 0.1.0
# Authors@R: person("Andy", "South", , "southandy@gmail.com", role = c("aut", "cre"))
# Description: Vector map data from <http://www.naturalearthdata.com/>. Access functions are provided in the accompanying package 'rnaturalearth'.
# License: CC0
# LazyData: true
# LazyDataCompression: xz
# URL: https://github.com/ropenscilabs/rnaturalearthdata
# BugReports: https://github.com/ropenscilabs/rnaturalearthdata/issues
# Depends: R (>= 3.1.1)
# Imports: sp (>= 1.0.15)
# Suggests: knitr (>= 1.12.3), testthat (>= 0.9.1)
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-02-21 13:45:59 UTC; andy
# Author: Andy South [aut, cre]
# Maintainer: Andy South <southandy@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-02-21 15:17:10

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
